version: '3.9'

services:
  backend:
    container_name: nodejs_backend
    image: nodejs
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - write-db
      - refresh-token-ids-storage
      - read-db
  write-db:
    container_name: write-db
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASS
    volumes:
      - ./docker/scripts/init-write-db.sh:/docker-entrypoint-initdb.d/init-write-db.sh
  refresh-token-ids-storage:
    container_name: refresh-token-ids-storage
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  read-db:
    container_name: read-db
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"

  # event-store:
  #   image: mongo:6.0.4
  #   ports:
  #     - 27018:27017
  #   environment:
  #     - MONGODB_DATABASE="vf-event-store"
  #   command: mongod --replSet vf-event-store-repl-set
  #   volumes:
  #     - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro