version: '3.9'

services:
  write-db:
    container_name: write-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASS
    volumes:
      - ./docker/scripts/init-write-db.sh:/docker-entrypoint-initdb.d/init-write-db.sh
  # read-db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGODB_DATABASE="vf-read-db"

  # event-store:
  #   image: mongo:6.0.4
  #   ports:
  #     - 27018:27017
  #   environment:
  #     - MONGODB_DATABASE="vf-event-store"
  #   command: mongod --replSet vf-event-store-repl-set
  #   volumes:
  #     - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro