#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL
	CREATE DATABASE $DATABASE_NAME;
	CREATE USER $DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$DATABASE_PASS';
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
  ALTER DATABASE $DATABASE_NAME OWNER TO $DATABASE_USERNAME;
EOSQL