#!/usr/bin/bash


psql -U postgres -c "CREATE DATABASE $DATABASE_NAME"
psql -U postgres -c "CREATE USER $DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$DATABASE_PASS'"
psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME"
psql -U postgres -c "ALTER DATABASE $DATABASE_NAME OWNER TO $DATABASE_USERNAME;"
