export enum ErrorMsg {
  // 共用錯誤
  ERR_COMMON_INVALID_OBJECT_ID = '10001 不合格的ObjectId請求',

  // Auth 登入相關
  ERR_AUTH_INVALID_ACCESS_TOKEN = '11001 無效的Access_Token',
  ERR_AUTH_SIGNUP_USER_CONFLICT = '11002 已註冊使用者',
  ERR_AUTH_SIGNIN_NOT_EXIST = '11003 尚未註冊使用者',
  ERR_AUTH_SIGNIN_PASSWORD = '11004 密碼錯誤',
  ERR_AUTH_SIGNUP_PASSWORD_CONFIRMED = '11005 確認密碼錯誤',
  ERR_AUTH_REFRESH_TOKEN_INVALID = '11006 無效刷新令牌',
  ERR_AUTH_USER_NOT_FOUND = '11007 找不到使用者',
  ERR_AUTH_ALREADY_ASK_FRIEND = '11008 已送出好友邀請',
  ERR_AUTH_USER_ALREADY_FRIEND = '11009 該使用者已經是好友',

  // 系統核心錯誤 相關錯誤
  ERR_CORE_UNKNOWN_ERROR = '99001 非預期系統錯誤',
}
